### ISSUE TITLE
Software license needed for sharing files

### ISSUE THREAD

**Issue by karenyyng** [matthewjackowski/pelican-dockerfile#1]
Hi, 

@matthewjackowski thanks for putting the Pelican Dockerfile together.
It looks wonderful but can you please add a license to your repo and docker image build?
Right now it is not legal for other people to use your code.

Thanks,
Karen

**Comment by matthewjackowski** [comment]
@karenyyng Thanks for pointing this out!  I added a permissive BSD-2 clause.  I'm glad you found this project useful!

**Comment by karenyyng** [comment]
I appreciate the quick response :)
